import { PrismaClient, CollegeType } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

const collegesData = [
  {
    name: "IIT Bombay",
    slug: "iit-bombay",
    type: CollegeType.IIT,
    stream: "Engineering",
    location: "Mumbai, Maharashtra",
    city: "Mumbai",
    state: "Maharashtra",
    emoji: "🏛️",
    bgGradient: "linear-gradient(135deg,#1a3a6b,#2d5ba0)",
    nirfRank: 3,
    rating: 4.8,
    reviewCount: 1240,
    established: 1958,
    intake: 1200,
    annualFees: 250000,
    feeDisplay: "₹2.5L/yr",
    avgPackage: 24.5,
    maxPackage: 120,
    placementRate: 95,
    overview:
      "IIT Bombay is one of India's premier engineering institutions, ranked consistently among the top 3 in NIRF rankings. Located in the heart of Mumbai, India's financial capital, students benefit from extraordinary industry exposure and networking opportunities. The institute is home to world-class research labs, 15 academic departments, and a vibrant startup ecosystem that has produced numerous unicorns.",
    accreditation: "NAAC A++",
    website: "https://www.iitb.ac.in",
    tags: ["Top Ranked", "Research Hub", "Dream Campus", "Startup Friendly"],
    courses: [
      { name: "B.Tech Computer Science", duration: "4 years", stream: "Engineering" },
      { name: "B.Tech Electrical Engineering", duration: "4 years", stream: "Engineering" },
      { name: "B.Tech Mechanical Engineering", duration: "4 years", stream: "Engineering" },
      { name: "M.Tech (Various)", duration: "2 years", stream: "Engineering" },
      { name: "MBA (SJMSOM)", duration: "2 years", stream: "Management" },
      { name: "PhD Programs", duration: "4-5 years", stream: "Research" },
    ],
    topRecruiters: ["Google", "Microsoft", "Amazon", "Goldman Sachs", "McKinsey"],
    reviews: [
      { rating: 5.0, text: "Best engineering college in India. World-class faculty and infrastructure. The peer group is exceptional and pushes you to be your best.", batch: "2023" },
      { rating: 4.8, text: "Incredible research opportunities and a campus that never sleeps. The entrepreneurship culture here is unmatched anywhere in Asia.", batch: "2022" },
    ],
  },
  {
    name: "IIT Delhi",
    slug: "iit-delhi",
    type: CollegeType.IIT,
    stream: "Engineering",
    location: "New Delhi, Delhi",
    city: "New Delhi",
    state: "Delhi",
    emoji: "🎓",
    bgGradient: "linear-gradient(135deg,#6b1a1a,#a02d2d)",
    nirfRank: 2,
    rating: 4.7,
    reviewCount: 1100,
    established: 1961,
    intake: 1100,
    annualFees: 220000,
    feeDisplay: "₹2.2L/yr",
    avgPackage: 22.3,
    maxPackage: 150,
    placementRate: 93,
    overview:
      "IIT Delhi, established in 1961, is ranked #2 in India by NIRF. Situated in the national capital, students enjoy unparalleled access to government bodies, corporate headquarters, and international embassies. The institute excels in both academic research and industry collaborations, with a thriving alumni network spread across Fortune 500 companies globally.",
    accreditation: "NAAC A++",
    website: "https://home.iitd.ac.in",
    tags: ["Top IIT", "Capital City", "Research", "Policy Making"],
    courses: [
      { name: "B.Tech Computer Science", duration: "4 years", stream: "Engineering" },
      { name: "B.Tech Electrical Engineering", duration: "4 years", stream: "Engineering" },
      { name: "B.Tech Mechanical Engineering", duration: "4 years", stream: "Engineering" },
      { name: "B.Des Design", duration: "4 years", stream: "Design" },
      { name: "MBA (DMS)", duration: "2 years", stream: "Management" },
    ],
    topRecruiters: ["Microsoft", "Apple", "Morgan Stanley", "McKinsey", "Bain"],
    reviews: [
      { rating: 4.7, text: "Being in Delhi gives amazing industry exposure. The placement record is consistently top-notch year after year.", batch: "2023" },
      { rating: 4.6, text: "The entrepreneurship cell here is phenomenal. Multiple unicorn startups have been founded by IITD alumni in the last 5 years.", batch: "2021" },
    ],
  },
  {
    name: "IIT Madras",
    slug: "iit-madras",
    type: CollegeType.IIT,
    stream: "Engineering",
    location: "Chennai, Tamil Nadu",
    city: "Chennai",
    state: "Tamil Nadu",
    emoji: "🌊",
    bgGradient: "linear-gradient(135deg,#1a5c4a,#2d8f74)",
    nirfRank: 1,
    rating: 4.7,
    reviewCount: 980,
    established: 1959,
    intake: 1000,
    annualFees: 230000,
    feeDisplay: "₹2.3L/yr",
    avgPackage: 21.8,
    maxPackage: 110,
    placementRate: 92,
    overview:
      "IIT Madras holds the #1 NIRF ranking for 6 consecutive years, a testament to its research excellence and academic rigor. Nestled within a protected forest reserve in Chennai, the campus is home to spotted deer and rare birds alongside cutting-edge research laboratories. IIT Madras pioneered India's first BS in Data Science program and houses the Deep Tech incubator.",
    accreditation: "NAAC A++",
    website: "https://www.iitm.ac.in",
    tags: ["#1 NIRF", "Coastal Campus", "Innovation", "Deep Tech"],
    courses: [
      { name: "B.Tech Computer Science", duration: "4 years", stream: "Engineering" },
      { name: "B.Tech Electrical Engineering", duration: "4 years", stream: "Engineering" },
      { name: "B.Tech Ocean Engineering", duration: "4 years", stream: "Engineering" },
      { name: "BS Data Science (Online)", duration: "3-6 years", stream: "Data Science" },
      { name: "M.Tech (Various)", duration: "2 years", stream: "Engineering" },
    ],
    topRecruiters: ["Qualcomm", "Texas Instruments", "Intel", "Flipkart", "Google"],
    reviews: [
      { rating: 4.9, text: "The campus is literally inside a forest reserve — absolutely stunning. Academic rigor here is unmatched.", batch: "2023" },
      { rating: 4.6, text: "Research ecosystem is world class. The incubation cell has produced over 300 startups. Truly the #1 engineering college in India.", batch: "2022" },
    ],
  },
  {
    name: "NIT Trichy",
    slug: "nit-trichy",
    type: CollegeType.NIT,
    stream: "Engineering",
    location: "Tiruchirappalli, Tamil Nadu",
    city: "Tiruchirappalli",
    state: "Tamil Nadu",
    emoji: "🔬",
    bgGradient: "linear-gradient(135deg,#3d1a6b,#6b2da0)",
    nirfRank: 8,
    rating: 4.4,
    reviewCount: 760,
    established: 1964,
    intake: 1800,
    annualFees: 180000,
    feeDisplay: "₹1.8L/yr",
    avgPackage: 14.2,
    maxPackage: 62,
    placementRate: 88,
    overview:
      "NIT Trichy is consistently ranked as the best NIT in India. Established in 1964, it has built an exceptional reputation for producing industry-ready engineers. The college's placement record rivals many IITs with companies like Microsoft, Amazon, and Goldman Sachs regularly recruiting here. Its affordable fees combined with stellar outcomes make it the best value engineering college in India.",
    accreditation: "NAAC A++",
    website: "https://www.nitt.edu",
    tags: ["Top NIT", "Affordable", "Strong Alumni", "Best Value"],
    courses: [
      { name: "B.Tech Computer Science", duration: "4 years", stream: "Engineering" },
      { name: "B.Tech Electronics & Communication", duration: "4 years", stream: "Engineering" },
      { name: "B.Tech Mechanical Engineering", duration: "4 years", stream: "Engineering" },
      { name: "B.Arch Architecture", duration: "5 years", stream: "Architecture" },
      { name: "M.Tech (Various)", duration: "2 years", stream: "Engineering" },
    ],
    topRecruiters: ["Microsoft", "Amazon", "Goldman Sachs", "L&T", "TCS"],
    reviews: [
      { rating: 4.5, text: "Best NIT in South India without question. Value for money is extraordinary given the placement stats and alumni network.", batch: "2023" },
      { rating: 4.3, text: "Faculty is experienced and approachable. Great balance of studies and cultural life. Placements rival many IITs.", batch: "2022" },
    ],
  },
  {
    name: "BITS Pilani",
    slug: "bits-pilani",
    type: CollegeType.DEEMED,
    stream: "Engineering",
    location: "Pilani, Rajasthan",
    city: "Pilani",
    state: "Rajasthan",
    emoji: "⚡",
    bgGradient: "linear-gradient(135deg,#6b4a1a,#a0782d)",
    nirfRank: 16,
    rating: 4.5,
    reviewCount: 890,
    established: 1964,
    intake: 2200,
    annualFees: 580000,
    feeDisplay: "₹5.8L/yr",
    avgPackage: 18.6,
    maxPackage: 95,
    placementRate: 90,
    overview:
      "BITS Pilani is India's top private engineering institute, renowned for its unique Practice School program that places students in industries for 5-6 months of real work experience. Founded by GD Birla in 1964, it offers unmatched curriculum flexibility allowing students to switch branches and pursue dual degrees. Its alumni form one of the strongest professional networks globally.",
    accreditation: "NAAC A",
    website: "https://www.bits-pilani.ac.in",
    tags: ["Practice School", "Flexible Curriculum", "Industry Ready", "Top Private"],
    courses: [
      { name: "B.E. Computer Science", duration: "4 years", stream: "Engineering" },
      { name: "B.E. Electronics & Communication", duration: "4 years", stream: "Engineering" },
      { name: "B.E. Mechanical", duration: "4 years", stream: "Engineering" },
      { name: "B.Pharm Pharmacy", duration: "4 years", stream: "Pharmacy" },
      { name: "M.Sc Mathematics + B.E. (Dual)", duration: "5 years", stream: "Dual Degree" },
    ],
    topRecruiters: ["Google", "Goldman Sachs", "DE Shaw", "Sprinklr", "Qualcomm"],
    reviews: [
      { rating: 4.6, text: "The Practice School program is absolutely unique and gives you real industry experience during college itself. Unmatched prep for placements.", batch: "2023" },
      { rating: 4.4, text: "Dual degree options and the flexibility to change majors is a huge advantage. Alumni network is one of the best anywhere in India.", batch: "2022" },
    ],
  },
  {
    name: "IIM Ahmedabad",
    slug: "iim-ahmedabad",
    type: CollegeType.DEEMED,
    stream: "Management",
    location: "Ahmedabad, Gujarat",
    city: "Ahmedabad",
    state: "Gujarat",
    emoji: "📊",
    bgGradient: "linear-gradient(135deg,#1a4a6b,#2d78a0)",
    nirfRank: 1,
    rating: 4.9,
    reviewCount: 650,
    established: 1961,
    intake: 400,
    annualFees: 2400000,
    feeDisplay: "₹24L/yr",
    avgPackage: 32.5,
    maxPackage: 250,
    placementRate: 100,
    overview:
      "IIM Ahmedabad is Asia's #1 business school and India's most prestigious management institute. Founded in 1961, IIMA pioneered the case-study method of management education in India. Its two-year PGP program transforms engineers and professionals into global business leaders. With 100% placement every year and an average package exceeding ₹32 LPA, IIMA represents the pinnacle of management education in South Asia.",
    accreditation: "AACSB, EQUIS",
    website: "https://www.iima.ac.in",
    tags: ["#1 MBA", "100% Placement", "Legacy", "Global Brand"],
    courses: [
      { name: "PGP (MBA equivalent)", duration: "2 years", stream: "Management" },
      { name: "PGPX (Executive MBA)", duration: "1 year", stream: "Management" },
      { name: "FPM (PhD)", duration: "4-5 years", stream: "Research" },
      { name: "Post Graduate Diploma in Agri-Business", duration: "2 years", stream: "Management" },
    ],
    topRecruiters: ["McKinsey", "BCG", "Bain", "Goldman Sachs", "Amazon"],
    reviews: [
      { rating: 5.0, text: "The case study method here is legendary. You get transformed into a business leader within the first 6 months. The peer learning is phenomenal.", batch: "2023" },
      { rating: 4.8, text: "Network and alumni connect is unbeatable. The IIMA brand opens doors literally anywhere in the world. Worth every rupee of the fees.", batch: "2022" },
    ],
  },
  {
    name: "VIT Vellore",
    slug: "vit-vellore",
    type: CollegeType.PRIVATE,
    stream: "Engineering",
    location: "Vellore, Tamil Nadu",
    city: "Vellore",
    state: "Tamil Nadu",
    emoji: "🌐",
    bgGradient: "linear-gradient(135deg,#1a6b3a,#2da05c)",
    nirfRank: 11,
    rating: 4.2,
    reviewCount: 2100,
    established: 1984,
    intake: 6500,
    annualFees: 420000,
    feeDisplay: "₹4.2L/yr",
    avgPackage: 8.4,
    maxPackage: 45,
    placementRate: 82,
    overview:
      "VIT Vellore is one of India's largest private engineering universities, with a sprawling 375-acre campus. Known for its state-of-the-art infrastructure, VIT attracts students from 50+ countries making it one of the most diverse campuses in Asia. The annual TechFest 'Gravitas' is one of Asia's largest technical festivals. VIT's FFCS curriculum system offers students maximum flexibility in choosing courses.",
    accreditation: "NAAC A++",
    website: "https://vit.ac.in",
    tags: ["Large Campus", "Tech Fest", "International", "Flexible Curriculum"],
    courses: [
      { name: "B.Tech Computer Science", duration: "4 years", stream: "Engineering" },
      { name: "B.Tech CSE (AI & ML)", duration: "4 years", stream: "Engineering" },
      { name: "B.Tech Biotechnology", duration: "4 years", stream: "Engineering" },
      { name: "B.Tech Information Technology", duration: "4 years", stream: "Engineering" },
      { name: "MBA", duration: "2 years", stream: "Management" },
    ],
    topRecruiters: ["TCS", "Cognizant", "HCL", "Capgemini", "Infosys"],
    reviews: [
      { rating: 4.2, text: "Massive campus with all modern facilities. TechFest Gravitas is one of the biggest in Asia. International exposure is a real highlight.", batch: "2023" },
      { rating: 4.0, text: "Good for average students who want stable placements. The peer network is very large. Infrastructure is world-class for a private college.", batch: "2022" },
    ],
  },
  {
    name: "AIIMS Delhi",
    slug: "aiims-delhi",
    type: CollegeType.CENTRAL,
    stream: "Medical",
    location: "New Delhi, Delhi",
    city: "New Delhi",
    state: "Delhi",
    emoji: "⚕️",
    bgGradient: "linear-gradient(135deg,#6b1a3d,#a02d5f)",
    nirfRank: 1,
    rating: 4.8,
    reviewCount: 540,
    established: 1956,
    intake: 107,
    annualFees: 1390,
    feeDisplay: "₹1,390/yr",
    avgPackage: 12.5,
    maxPackage: 45,
    placementRate: 98,
    overview:
      "AIIMS Delhi is Asia's premier medical institution and the most coveted destination for NEET toppers. Government-funded, its annual fees are just ₹1,390 — an extraordinary bargain for the world-class education it offers. Graduates are in immense demand across top hospitals globally. The sheer volume and complexity of patients treated makes AIIMS graduates among the most skilled clinicians in the world.",
    accreditation: "MCI Approved",
    website: "https://www.aiims.edu",
    tags: ["Top Medical", "Govt Funded", "Research", "Ultra Low Fees"],
    courses: [
      { name: "MBBS", duration: "5.5 years", stream: "Medical" },
      { name: "MD Various Specializations", duration: "3 years", stream: "Medical" },
      { name: "MS Surgery", duration: "3 years", stream: "Medical" },
      { name: "B.Sc Nursing", duration: "4 years", stream: "Nursing" },
    ],
    topRecruiters: ["AIIMS Hospitals", "Max Healthcare", "Apollo Hospitals", "Fortis"],
    reviews: [
      { rating: 5.0, text: "The best medical college in Asia, no debate. Learning under top professors and handling complex cases from day one is an unreal experience.", batch: "2023" },
      { rating: 4.7, text: "Government funded so fees are negligible. The sheer volume and variety of patients gives hands-on experience impossible to find anywhere else.", batch: "2021" },
    ],
  },
  {
    name: "IIT Kharagpur",
    slug: "iit-kharagpur",
    type: CollegeType.IIT,
    stream: "Engineering",
    location: "Kharagpur, West Bengal",
    city: "Kharagpur",
    state: "West Bengal",
    emoji: "🔭",
    bgGradient: "linear-gradient(135deg,#1a3d6b,#2d5f8f)",
    nirfRank: 5,
    rating: 4.6,
    reviewCount: 870,
    established: 1951,
    intake: 2000,
    annualFees: 240000,
    feeDisplay: "₹2.4L/yr",
    avgPackage: 20.1,
    maxPackage: 130,
    placementRate: 91,
    overview:
      "IIT Kharagpur, established in 1951, is the oldest and largest IIT in India. Its 2,100-acre campus — the size of a small city — houses 19 departments, 8 schools, and over 22,000 students. The Technology Student Gymkhana runs 40+ clubs and societies. IIT KGP alumni lead major organizations globally, and the institute has produced more CEOs than any other engineering college in India.",
    accreditation: "NAAC A",
    website: "https://www.iitkgp.ac.in",
    tags: ["Oldest IIT", "Largest Campus", "Heritage", "Most CEOs"],
    courses: [
      { name: "B.Tech Computer Science", duration: "4 years", stream: "Engineering" },
      { name: "B.Tech Architecture", duration: "5 years", stream: "Architecture" },
      { name: "B.Tech Law (Integrated)", duration: "5 years", stream: "Law" },
      { name: "MBA (VGSOM)", duration: "2 years", stream: "Management" },
      { name: "M.Tech (Various)", duration: "2 years", stream: "Engineering" },
    ],
    topRecruiters: ["Microsoft", "Google", "Amazon", "Intel", "Jaguar Land Rover"],
    reviews: [
      { rating: 4.6, text: "Oldest IIT with a campus so massive it has its own railway station. Technology Student's Gymkhana clubs are truly legendary.", batch: "2023" },
      { rating: 4.5, text: "Excellent infrastructure and one of the strongest alumni networks in the world. KGPians dominate C-suites globally.", batch: "2022" },
    ],
  },
  {
    name: "NIT Warangal",
    slug: "nit-warangal",
    type: CollegeType.NIT,
    stream: "Engineering",
    location: "Warangal, Telangana",
    city: "Warangal",
    state: "Telangana",
    emoji: "🏗️",
    bgGradient: "linear-gradient(135deg,#6b3a1a,#a05c2d)",
    nirfRank: 10,
    rating: 4.3,
    reviewCount: 620,
    established: 1959,
    intake: 1500,
    annualFees: 170000,
    feeDisplay: "₹1.7L/yr",
    avgPackage: 13.5,
    maxPackage: 58,
    placementRate: 86,
    overview:
      "NIT Warangal, the second oldest NIT in India, has built an exceptional reputation for core engineering excellence. Companies like Microsoft, Amazon, and Goldman Sachs regularly recruit from its campus. The college's low fees combined with top-tier placements make it one of the best return-on-investment choices in Indian engineering education.",
    accreditation: "NAAC A++",
    website: "https://www.nitw.ac.in",
    tags: ["Affordable NIT", "Strong Core Engg", "Alumni Network", "Top ROI"],
    courses: [
      { name: "B.Tech Computer Science", duration: "4 years", stream: "Engineering" },
      { name: "B.Tech Mechanical Engineering", duration: "4 years", stream: "Engineering" },
      { name: "B.Tech Civil Engineering", duration: "4 years", stream: "Engineering" },
      { name: "B.Tech Electronics", duration: "4 years", stream: "Engineering" },
      { name: "M.Tech (Various)", duration: "2 years", stream: "Engineering" },
    ],
    topRecruiters: ["Microsoft", "Amazon", "TCS", "L&T", "ONGC"],
    reviews: [
      { rating: 4.4, text: "Second oldest NIT with excellent placement record. Core engineering companies love NIT Warangal graduates for their strong fundamentals.", batch: "2023" },
      { rating: 4.2, text: "Faculty is very dedicated and placements have been improving consistently every year. Affordable fees with great outcomes.", batch: "2022" },
    ],
  },
  {
    name: "Manipal Institute of Technology",
    slug: "manipal-institute",
    type: CollegeType.DEEMED,
    stream: "Engineering",
    location: "Manipal, Karnataka",
    city: "Manipal",
    state: "Karnataka",
    emoji: "🌴",
    bgGradient: "linear-gradient(135deg,#1a5a4a,#2d8a72)",
    nirfRank: 45,
    rating: 4.0,
    reviewCount: 1450,
    established: 1957,
    intake: 4000,
    annualFees: 550000,
    feeDisplay: "₹5.5L/yr",
    avgPackage: 7.8,
    maxPackage: 42,
    placementRate: 78,
    overview:
      "Manipal Institute of Technology is part of the prestigious Manipal University and is located in the picturesque coastal town of Manipal, Karnataka. Known for having some of the best campus life in India, MIT Manipal offers a diverse range of programs and attracts international students. The college town atmosphere with its restaurants, beaches, and student community makes it a memorable experience.",
    accreditation: "NAAC A+",
    website: "https://manipal.edu/mit.html",
    tags: ["Best Campus Life", "International Students", "Coastal", "Diverse Programs"],
    courses: [
      { name: "B.Tech Computer Science", duration: "4 years", stream: "Engineering" },
      { name: "MBBS", duration: "5.5 years", stream: "Medical" },
      { name: "BBA Business Administration", duration: "3 years", stream: "Management" },
      { name: "B.Arch Architecture", duration: "5 years", stream: "Architecture" },
      { name: "B.Pharm Pharmacy", duration: "4 years", stream: "Pharmacy" },
    ],
    topRecruiters: ["Infosys", "Wipro", "UST Global", "Oracle", "Accenture"],
    reviews: [
      { rating: 4.1, text: "Best campus life in India, full stop. The college town of Manipal is an experience in itself — beaches, great food, amazing community.", batch: "2023" },
      { rating: 3.9, text: "Great for diverse courses and excellent infrastructure. Fees are on the higher side but the overall college experience justifies it.", batch: "2022" },
    ],
  },
  {
    name: "Delhi University (SRCC)",
    slug: "delhi-university-srcc",
    type: CollegeType.CENTRAL,
    stream: "Management",
    location: "New Delhi, Delhi",
    city: "New Delhi",
    state: "Delhi",
    emoji: "🏫",
    bgGradient: "linear-gradient(135deg,#4a1a6b,#782da0)",
    nirfRank: 12,
    rating: 4.1,
    reviewCount: 980,
    established: 1922,
    intake: 70000,
    annualFees: 25000,
    feeDisplay: "₹25K/yr",
    avgPackage: 6.2,
    maxPackage: 28,
    placementRate: 75,
    overview:
      "Delhi University, established in 1922, is one of India's most prestigious central universities. Colleges like SRCC (Shri Ram College of Commerce) and LSR (Lady Shri Ram) are among the most coveted undergraduate destinations. DU offers world-class arts, commerce, and science education at negligible cost. The university's location in Delhi, combined with its century-long heritage, creates an unmatched alumni network.",
    accreditation: "NAAC A++",
    website: "https://www.du.ac.in",
    tags: ["Heritage", "Ultra Affordable", "Central Location", "Diverse Courses"],
    courses: [
      { name: "B.Com (Honours)", duration: "3 years", stream: "Commerce" },
      { name: "BA Economics (Honours)", duration: "3 years", stream: "Economics" },
      { name: "BMS Business Management Studies", duration: "3 years", stream: "Management" },
      { name: "B.Tech (NSUT, DTU)", duration: "4 years", stream: "Engineering" },
      { name: "LLB Law", duration: "3 years", stream: "Law" },
    ],
    topRecruiters: ["KPMG", "EY", "Deloitte", "Goldman Sachs", "BCG"],
    reviews: [
      { rating: 4.2, text: "DU colleges like SRCC and LSR have incredible alumni networks. The fees are remarkably low for the quality of education and opportunities.", batch: "2023" },
      { rating: 4.0, text: "The diversity of students from across India makes it a truly unique cultural experience. Delhi location means endless internship opportunities.", batch: "2022" },
    ],
  },
];

async function main() {
  console.log("🌱 Starting seed...");

  // Create demo user
  const passwordHash = await bcrypt.hash("demo1234", 12);
  const user = await prisma.user.upsert({
    where: { email: "demo@campass.in" },
    update: {},
    create: {
      email: "demo@campass.in",
      name: "Demo User",
      passwordHash,
    },
  });
  console.log("✅ Demo user created:", user.email);

  // Seed colleges
  for (const collegeData of collegesData) {
    const { tags, courses, topRecruiters, reviews, ...college } = collegeData;

    const created = await prisma.college.upsert({
      where: { slug: college.slug },
      update: {},
      create: {
        ...college,
        tags: {
          create: tags.map((label) => ({ label })),
        },
        courses: {
          create: courses,
        },
        topRecruiters: {
          create: topRecruiters.map((name) => ({ name })),
        },
        reviews: {
          create: reviews.map((r) => ({
            ...r,
            userId: user.id,
          })),
        },
      },
    });
    console.log(`✅ College seeded: ${created.name}`);
  }

  console.log("🎉 Seed complete!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
